version: "3.8"

services:
  backend:
    build:
      context: ./backend-api
    ports:
      - "5000:8080"  # .NET app inside container exposes 8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  frontend:
    build:
      context: ./frontend-app
    ports:
      - "3000:3000"  # React app exposed on port 3000
    depends_on:
      - backend